[package]
name = "gen-img-manager"
version = "0.1.1"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "gen_img_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
gim-core = { path = "../crates/core" }
tauri = { version = "2", features = ["protocol-asset"] }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
tauri-plugin-dialog = "2"
image = { workspace = true }
webp = { workspace = true }
png = "0.18"
walkdir = "2"
kamadak-exif = "0.6"
quick-xml = "0.39"
thiserror = { workspace = true }
rayon = "1"
chrono = { workspace = true }
trash = "5"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-window-state = "2.4.1"

